version: '3.8'
services:
    db:
      image: postgres:17
      environment:
        POSTGRES_DB: jobtracker_db
        POSTGRES_USER: jaysimpson
        POSTGRES_PASSWORD: OGbaconsauce1$
      ports:
        - "5432:5432"

    backend:
      build: ./BackEnd
      ports:
        - "8080:8080"

      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobtracker_db
        SPRING_DATASOURCE_USERNAME: jaysimpson
        SPRING_DATASOURCE_PASSWORD: OGbaconsauce1$
      depends_on:
        - db

